## Домашнее задание 1 (5 баллов)

Все задания ниже имеют равный вес (5/10).

### О задании

В этом домашнем задании вы попрактикуетесь в работе с библиотекой numpy, которая позволяет сравнительно легко и удобно выполнять разнообразные вычисления, избегая самостоятельной реализации поэлементной обработки.

Во всех задачах необходимо написать код решения внутри функции и убедиться, что она работает, с помощью [assert](https://python-reference.readthedocs.io/en/latest/docs/statements/assert.html) на выражение с использованием этой функции для данных из условия.

При решении задач запрещается использовать циклы (`for`, `while`) и оператор `if`. Да, `map`, `reduce`, `filter` и любые другие "чисто питоновские" конструкции тоже запрещены. **Используйте только функционал numpy**.

Везде, где встречаются массивы или матрицы, подразумевается, что это `numpy.array`.

**numpy reference:** https://numpy.org/doc/stable/reference/index.html

In [6]:
import numpy as np

### Задание 1

Напишите функцию, возвращающую округленную взвешенную сумму оценок по данным оценкам и весам. Можете посчитать свою оценку за курс :) В нашем случае вес экзамена равен 0.3, вес домашек - 0.4, вес контрольной - 0.2, вес самостоятельных - 0.1. Например, если за экзамен у вас 7, за домашки 10, за контрольную 8, а за самостоятельные 6, то вы получите отличную оценку 8!

Обратите внимание, что на вход приходит всегда двумерный массив. В нем в каждой строке - окенки одного конкретного студента. От вас требуется вернуть итоговую оценку для всех студентов в массиве.

In [33]:
def result_mark(weights: np.array, marks: np.array) -> int:
    res = np.sum(weights * marks, axis=1)
    print(res)
    return res.astype(int)

In [35]:
weights = np.array([0.3, 0.4, 0.2, 0.1])
marks = np.array([[7, 10, 8, 6], [6, 9, 7, 6]])

assert np.allclose(result_mark(weights, marks), np.array([8, 7]))

[8.3 7.4]


In [37]:
weights = np.array([0.3, 0.4, 0.2, 0.1])
marks = np.array([[7, 0, 8, 6]])

assert np.allclose(result_mark(weights, marks), np.array([4]))

[4.3]


### Задание 2

Напишите функцию, которая каждое четное число в массиве заменяет на его квадрат (вторую степень), а нечетное - на его синус. Округлите все значения в итоговом массиве до двух знаков после запятой.

In [103]:
def change_array(array: np.array) -> np.array:
    array = np.where(array % 2 == 0, array ** 2, np.sin(array))
    return np.round(array, 2)

In [105]:
array = np.array([2, 5, 1, 0, -6, 22, 213431])

assert np.allclose(change_array(array), np.array([4.0, -0.96, 0.84, 0.0, 36.0, 484.0, -0.58]))

In [107]:
array = np.array([3, 12, 15, -97, 6])

assert np.allclose(change_array(array), np.array([0.14, 144.0, 0.65, -0.38, 36.0]))

### Задание 3

Напишите функцию, которая вычисляет разность каждого элемента с предыдущим (для самого первого считайте, что его разница с "предыдущим" нулевая) в виде нового массива и возвращает вектор, в котором каждый новый элемент - сумма всех предыдущих из полученного нового массива.

In [189]:
def cumulative_sum_of_differences(array):
    arr = np.ediff1d(array, to_begin=0)
    return np.cumsum(arr)

In [191]:
array = np.array([3, 6, 2, 8])

assert np.allclose(cumulative_sum_of_differences(array), np.array([0, 3, -1, 5]))

In [193]:
array = np.array([5, 1])

assert np.allclose(cumulative_sum_of_differences(array), np.array([0, -4]))

### Задание 4

Напишите функцию, которая транспонирует двумерный массив, затем делает из него одномерный (reshape), переводит все элементы массива в *int8* и выводит его отсортированным по убыванию.

In [265]:
def flatten_and_sort_transposed(array: np.array) -> np.array:
    a = array.T
    a = a.reshape(-1)
    b = a.astype(np.int8)
    b = np.sort(b)[::-1]
    
    return b

In [267]:
array = np.array([[256, -10], [-381, 112]])

assert np.allclose(flatten_and_sort_transposed(array), np.array([112, 0, -10, -125]))

In [269]:
array = np.array([[9, 8, 7], [3, 6, 129]])

assert np.allclose(flatten_and_sort_transposed(array), np.array([ 9, 8, 7, 6, 3, -127]))

### Задание 5

Напишите функцию, которая удаляет из массива все строки, среднее значение в которых больше общего среднего значения по всему массиву.

In [317]:
def filter_rows_by_mean(array):
    arr = array[array.mean() >= array.mean(axis=1)]
    # print(arr)
    return arr

In [319]:
array = np.array([[1, 2, 3], [7, 8, 9], [4, 5, 6]])
res = filter_rows_by_mean(array)

assert res.ndim == 2
assert np.allclose(res, np.array([[1, 2, 3], [4, 5, 6]]))

[[1 2 3]
 [4 5 6]]


In [321]:
array = np.array([[10, 20], [5, 5], [15, 15]])
res = filter_rows_by_mean(array)

assert res.ndim == 2
assert np.allclose(res, np.array([[5, 5]]))

[[5 5]]


### Задание 6

Напишите функцию, которая принимает на вход число - размер массива (квадратная матрица), который заполнен по принипу щахматной доски нулями и единицами. Первой (слева сверху) идет всегда единица. Напомним, что на шахматной доске белые и черные ячейки чередуются (в данном задании чередуются нули и единицы).

In [537]:
def create_checkerboard(number):
    arr = np.ones([number, number])
    arr = lambda x, y: if x % 2 
    print(arr)
    return arr

In [539]:
number = 3

assert np.allclose(create_checkerboard(number) - np.array([[1, 0, 1], [0, 1, 0], [1, 0, 1]]), np.zeros((number, number)))

[[1. 0. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


AssertionError: 

In [495]:
number = 4

assert np.allclose(create_checkerboard(number) - np.array([[1, 0, 1, 0], [0, 1, 0, 1], [1, 0, 1, 0], [0, 1, 0, 1]]), np.zeros((number, number)))

IndexError: too many indices for array: array is 2-dimensional, but 3 were indexed

### Задание 7

Напишите функцию, которая соритрует строки двумерного массива по значению в первом (начиная с нуля) столбце (по возрастанию).

In [ ]:
def sort_rows_by_second_column(array):
    # your code here

In [90]:
array = np.array([[10, 2], [3, 5], [7, 1]])

assert np.allclose(sort_rows_by_second_column(array), np.array([[7, 1], [10, 2], [3, 5]]))

In [91]:
array = np.array([[5, 8, 1], [10, 3, 9], [2, 7, 0], [6, -1, 5]])

assert np.allclose(sort_rows_by_second_column(array), np.array([[6, -1, 5], [10, 3, 9], [2, 7, 0], [5, 8, 1]]))

### Задание 8

Напишите функцию, которая вычисляет сумму элементов [побочной](https://ru.wikipedia.org/wiki/Квадратная_матрица) диагонали квадратной матрицы.

In [566]:
def sum_counterdiagonal_elements(array):
    return np.trace(array[:, ::-1])

In [568]:
array = np.array([[5, 8, 1], [10, 3, 9], [2, 7, 0]])

assert sum_counterdiagonal_elements(array) == 6

In [564]:
array = np.array([[-4, -1, -1, 7], [6, -10, 5, -9], [3, -8, 6, 8], [-1, -6, 7, -10]])

assert sum_counterdiagonal_elements(array) == 3

3


AssertionError: 

### Задание 9

Напишите функцию, которая принимает на вход три числа (начало отрезка, конец отрезка, количество точек на отрезке). Данная функция генерирует указанное количество точек равномерно на отрезке с указанными концами (точки равноудалены друг от друга). Затем функция генерирует другой массив - натуральный логарифм от всех точек отрезка плюс единица ($ln(point + 1)$). Возвращает функция массив пар точек вида (точка на отрезке, ее логарифм). Каждое значение в возвращаемом массиве должно быть округлено до двух знаков после запятой.

In [758]:
def generate_logarithm_points(start, end, count):
    arr = np.arange(start, end)
    arr = arr.astype(float)
    arr2 = np.round(np.log(arr + 1), 2)
    res = np.stack((arr, arr2), axis=1).shape(1)
    print(res)
    return res

In [760]:
start = 1
end = 10
count = 5

assert np.allclose(generate_logarithm_points(start, end, count), np.array([[1., 0.69], [3.25, 1.45], [5.5 , 1.87], [7.75, 2.17], [10., 2.4]]))

TypeError: 'tuple' object is not callable

In [762]:
start = 5
end = 12
count = 4

assert np.allclose(generate_logarithm_points(start, end, count), np.array([[5., 1.79], [7.33, 2.12], [9.67, 2.37], [12., 2.56]]))

TypeError: 'tuple' object is not callable

### Задание 10

Напишите функцию, которая нормализует входной двумерный массив. 

Под нормализацией в данном задании подразумевается перевод всех чисел массива на отрезок $[0; 1]$. Очевидно, недостаточно просто вычесть/прибавить лишнее, чтобы остались числа на нужном отрезке. Суть нормализации массива в том, чтобы не потерять информацию о его элементах и их соотношениях. Потому, необходимо сохранить пропорции расстояний между каждым числом - спроецировать все точки на указанный отрезок. Такой метод масштабирования массива называется MinMaxScaling. Само название дает подсказку, как нужно решить задачу. Дробные числа округляйте до двух знаков после запятой.

*Будьте осторожны с делением...*

In [810]:


def min_max_scale(array):
    res = (array - np.min(array)) / (np.max(array) - np.min(array, axis=1, keepdims=True)))
    # print(array - np.min(array, axis=1, keepdims=True), np.max(array, axis=1, keepdims=True), np.min(array, axis=1, keepdims=True), sep="\n")
    print(res)

In [812]:
array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

assert np.allclose(min_max_scale(array), np.array([[0. , 0.12, 0.25], [0.38, 0.5 , 0.62], [0.75, 0.88, 1.]]))

[[0.  0.5 1. ]
 [0.  0.5 1. ]
 [0.  0.5 1. ]]


TypeError: ufunc 'isfinite' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

In [100]:
array = np.array([[0, 1, 2], [3, 4, 5]])

assert np.allclose(min_max_scale(array), np.array([[0., 0.2, 0.4], [0.6, 0.8, 1.]]))